export default {
  title: 'Over the River and Through the Woods',
  url: 'over-the-river-and-through-the-woods',
  notes: [
    { note: 'G', octave: 4, lyric: 'O-' },
    { note: 'G', octave: 4, lyric: 'ver' },
    { note: 'G', octave: 4, lyric: 'the' },
    { note: 'G', octave: 4, lyric: ' ri-' },
    { note: 'E', octave: 4, lyric: 'ver' },
    { note: 'F', octave: 4, lyric: 'and' },
    { note: 'G', octave: 4, lyric: 'through' },
    { note: 'A', octave: 4, lyric: 'the' },
    { note: 'G', octave: 4, lyric: ' woods' },
    { note: 'G', octave: 4, lyric: 'to' },
    { note: 'C', octave: 5, lyric: 'Grand-' },
    { note: 'C', octave: 5, lyric: 'mo-' },
    { note: 'C', octave: 5, lyric: "ther's" },
    { note: 'B', octave: 4, lyric: 'house' },
    { note: 'A', octave: 4, lyric: 'we' },
    { note: 'G', octave: 4, lyric: 'go.' },
    { note: 'E', octave: 4, lyric: 'The' },
    { note: 'F', octave: 4, lyric: 'horse' },
    { note: 'F', octave: 4, lyric: 'knows' },
    { note: 'F', octave: 4, lyric: 'the' },
    { note: 'F', octave: 4, lyric: 'way ' },
    { note: 'D', octave: 4, lyric: 'to ' },
    { note: 'E', octave: 4, lyric: 'car-' },
    { note: 'E', octave: 4, lyric: 'ry' },
    { note: 'E', octave: 4, lyric: 'the ' },
    { note: 'E', octave: 4, lyric: 'sleigh' },
    { note: 'E', octave: 4, lyric: 'through' },
    { note: 'E', octave: 4, lyric: 'the' },
    { note: 'E', octave: 4, lyric: 'white' },
    { note: 'D', octave: 4, lyric: 'and' },
    { note: 'D', octave: 4, lyric: 'drift-' },
    { note: 'E', octave: 4, lyric: 'ed' },
    { note: 'D', octave: 4, lyric: 'snow-' },
    { note: 'G', octave: 4, lyric: 'oh!' },
    { note: 'G', octave: 4, lyric: 'O-' },
    { note: 'G', octave: 4, lyric: 'ver' },
    { note: 'G', octave: 4, lyric: 'the' },
    { note: 'G', octave: 4, lyric: 'ri-' },
    { note: 'E', octave: 4, lyric: 'ver' },
    { note: 'F', octave: 4, lyric: 'and' },
    { note: 'G', octave: 4, lyric: 'through' },
    { note: 'A', octave: 4, lyric: 'the' },
    { note: 'G', octave: 4, lyric: 'woods,' },
    { note: 'G', octave: 4, lyric: 'Oh,' },
    { note: 'C', octave: 5, lyric: 'how ' },
    { note: 'C', octave: 5, lyric: 'the' },
    { note: 'B', octave: 4, lyric: 'wind' },
    { note: 'A', octave: 4, lyric: 'does' },
    { note: 'G', octave: 4, lyric: 'blow!' },
    { note: 'G', octave: 4, lyric: 'It' },
    { note: 'C', octave: 5, lyric: 'stings' },
    { note: 'C', octave: 5, lyric: 'the ' },
    { note: 'B', octave: 4, lyric: 'toes' },
    { note: 'A', octave: 4, lyric: ' and' },
    { note: 'G', octave: 4, lyric: 'bites' },
    { note: 'E', octave: 4, lyric: 'the ' },
    { note: 'C', octave: 4, lyric: 'nose' },
    { note: 'D', octave: 4, lyric: 'as ' },
    { note: 'E', octave: 4, lyric: 'o-' },
    { note: 'G', octave: 4, lyric: 'ver' },
    { note: 'F', octave: 4, lyric: 'the' },
    { note: 'E', octave: 4, lyric: 'ground' },
    { note: 'D', octave: 4, lyric: 'we' },
    { note: 'C', octave: 5, lyric: 'go.' }
  ]
};
